/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasindividu;

import javax.swing.JFrame;

/**
 *
 * @author Amelia
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyatas = new javax.swing.JPanel();
        BOliy = new javax.swing.JButton();
        BDry = new javax.swing.JButton();
        Bcombi = new javax.swing.JButton();
        rutin = new javax.swing.JButton();
        BHome = new javax.swing.JButton();
        bodybawah = new javax.swing.JPanel();
        aboutme = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Toil = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Tkombi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Trutin = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        Tdry = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyatas.setBackground(new java.awt.Color(255, 255, 204));

        BOliy.setBackground(new java.awt.Color(204, 204, 204));
        BOliy.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        BOliy.setForeground(new java.awt.Color(0, 153, 102));
        BOliy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/face1.png"))); // NOI18N
        BOliy.setText("Dry Skin");
        BOliy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        BOliy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOliyActionPerformed(evt);
            }
        });

        BDry.setBackground(new java.awt.Color(204, 204, 204));
        BDry.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        BDry.setForeground(new java.awt.Color(0, 153, 102));
        BDry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/face2.png"))); // NOI18N
        BDry.setText("Oily Skin");
        BDry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        BDry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDryActionPerformed(evt);
            }
        });

        Bcombi.setBackground(new java.awt.Color(204, 204, 204));
        Bcombi.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Bcombi.setForeground(new java.awt.Color(0, 153, 102));
        Bcombi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/face3.png"))); // NOI18N
        Bcombi.setText("Combination Skin");
        Bcombi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Bcombi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcombiActionPerformed(evt);
            }
        });

        rutin.setBackground(new java.awt.Color(204, 204, 204));
        rutin.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        rutin.setForeground(new java.awt.Color(0, 153, 102));
        rutin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/face4.png"))); // NOI18N
        rutin.setText("Routine");
        rutin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        rutin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutinActionPerformed(evt);
            }
        });

        BHome.setBackground(new java.awt.Color(204, 204, 204));
        BHome.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        BHome.setForeground(new java.awt.Color(0, 153, 102));
        BHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/about.png"))); // NOI18N
        BHome.setText("About Me");
        BHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        BHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyatasLayout = new javax.swing.GroupLayout(bodyatas);
        bodyatas.setLayout(bodyatasLayout);
        bodyatasLayout.setHorizontalGroup(
            bodyatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyatasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BHome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BOliy, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BDry, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Bcombi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rutin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        bodyatasLayout.setVerticalGroup(
            bodyatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyatasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BOliy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BDry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bcombi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rutin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(bodyatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 780, 60));

        bodybawah.setBackground(new java.awt.Color(255, 153, 153));
        bodybawah.setLayout(new java.awt.CardLayout());

        aboutme.setBackground(new java.awt.Color(102, 204, 153));

        jLabel18.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 204));
        jLabel18.setText("TEMPAT TANGGAL LAHIR : JAKARTA 1 SEPTEMBER 1998");

        jLabel19.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 204));
        jLabel19.setText("NAMA : PUTRI AYU AMELIA");

        jLabel20.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 204));
        jLabel20.setText("GOL : O");

        jLabel21.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 204));
        jLabel21.setText("HOBI : NONTON FILM ACTION");

        jLabel22.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 204));
        jLabel22.setText("FAKULTAS : TEKNIK DAN ILMU KOMPUTER");

        jLabel23.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 204));
        jLabel23.setText("JURUSAN : TEKNIK INFORMATIKA");

        jLabel25.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 204));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/email.png"))); // NOI18N
        jLabel25.setText("PUTRIAYUAMELIA19@GMAIL.COM");

        jLabel26.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 204));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/ig.png"))); // NOI18N
        jLabel26.setText("AMELODIESS");

        jLabel27.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 204));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/twitter (1).png"))); // NOI18N
        jLabel27.setText("PTRIAYUAMELIA");

        javax.swing.GroupLayout aboutmeLayout = new javax.swing.GroupLayout(aboutme);
        aboutme.setLayout(aboutmeLayout);
        aboutmeLayout.setHorizontalGroup(
            aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutmeLayout.createSequentialGroup()
                .addGroup(aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutmeLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)))
                    .addGroup(aboutmeLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutmeLayout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(375, Short.MAX_VALUE)))
            .addGroup(aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutmeLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel26)
                    .addContainerGap(590, Short.MAX_VALUE)))
        );
        aboutmeLayout.setVerticalGroup(
            aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutmeLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutmeLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(371, Short.MAX_VALUE)))
            .addGroup(aboutmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutmeLayout.createSequentialGroup()
                    .addContainerGap(385, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );

        bodybawah.add(aboutme, "card3");

        Toil.setBackground(new java.awt.Color(0, 153, 153));

        jTextArea2.setBackground(new java.awt.Color(0, 153, 153));
        jTextArea2.setColumns(10);
        jTextArea2.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 204));
        jTextArea2.setRows(5);
        jTextArea2.setText("Masalah yang biasanya mengikuti problem kulit berminyak adalah pori-pori besar, \njerawat, bruntusan, dan komedo. Perlu diingat bahwa ukuran pori-pori dipengaruhi\noleh faktor genetik dan pori-pori juga nggak bisa membesar atau mengecil,\njadi kurang tepat kalau kamu spesifik mencari skincare yang bisa “mengecilkan pori-pori”.\n\n\t1. Double cleansing, rutin eksfoliasi untuk merontokkan sel kulit mati.\n\t\n\t2. Jangan terlalu fokus pada skincare yang mengeringkan kulit.\n\t\n\t3. Jangan takut pakai pelembap.\n\n\t4. Cari sunscreen yang cocok untuk melindungi kulit.");
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel9.setFont(new java.awt.Font("DilleniaUPC", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/icons8-lips-40.png"))); // NOI18N
        jLabel9.setText("HELLO BEAUTYFULL");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/bery.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/fresh.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/naga.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/anggur.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/ceri.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/banana.png"))); // NOI18N

        javax.swing.GroupLayout ToilLayout = new javax.swing.GroupLayout(Toil);
        Toil.setLayout(ToilLayout);
        ToilLayout.setHorizontalGroup(
            ToilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToilLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(ToilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ToilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addGap(19, 19, 19))
            .addGroup(ToilLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ToilLayout.setVerticalGroup(
            ToilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToilLayout.createSequentialGroup()
                .addGroup(ToilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ToilLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addGroup(ToilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ToilLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel16)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel14))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ToilLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel15)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel12)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        bodybawah.add(Toil, "card4");

        Tkombi.setBackground(new java.awt.Color(153, 0, 102));

        jLabel10.setFont(new java.awt.Font("DilleniaUPC", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/icons8-lips-40.png"))); // NOI18N
        jLabel10.setText("HELLO BEUATYFULL\n");
        jLabel10.setIconTextGap(10);

        jTextArea3.setBackground(new java.awt.Color(153, 0, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(255, 255, 204));
        jTextArea3.setRows(5);
        jTextArea3.setText("Jika minyak terdapat pada daerah T wajah, dapat dipastikan kulit tersebut \nbertipe kombinasi, pada area T ini juga biasanya akan terlihat pori-pori yang\nlebih berar. Cara mengatasi hal tersebut yaitu:\n\n\t1. piliah cleanser dengan berbentuk lotion atau gel yang penting dapat \n\tmembersihkan wajah secara bersih tanpa membuat kulit terasa kering.\n\t\n\t2.Setelah menstabilkan PH wajah sebaikan gunakan toner wajah yang \n\tdapat menutrisi kulit kering sekaligus meminumalkan sebum pada saat yang sama.\n\t\n\t3. Gunakan skincare yang mengandung BHA\n\n");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout TkombiLayout = new javax.swing.GroupLayout(Tkombi);
        Tkombi.setLayout(TkombiLayout);
        TkombiLayout.setHorizontalGroup(
            TkombiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TkombiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(TkombiLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TkombiLayout.setVerticalGroup(
            TkombiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TkombiLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        bodybawah.add(Tkombi, "card5");

        Trutin.setBackground(new java.awt.Color(52, 73, 94));

        jLabel17.setFont(new java.awt.Font("DilleniaUPC", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 204));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/icons8-lips-40.png"))); // NOI18N
        jLabel17.setText("HELLO BEUATYFULL\n");
        jLabel17.setIconTextGap(10);

        jTextArea4.setBackground(new java.awt.Color(52, 73, 94));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 204));
        jTextArea4.setRows(5);
        jTextArea4.setText("\tKali ini aku akan share ke kalian tentang skincare pada malam hari yang aku \ngunakan sehari-hari sebelumnya tipe jenis kulit aku kombinasi di daera-daerah tertentu \nsaja yang berminyak selebihnya kulit ku benar-benar kering kadang sampai terkelupas.\n\t\n\tHal yang pertama ku lakukan membersihkan makeup dari wajah sebelum cuci muka\nbiasanya aku memakai CORINE DE FARME setelah bersih ku mencuci muka menggunakan ACNES\nsampai benar-benar kuliat merasa bersih biasanya 2 hari sekali aku melakukan scrub muka \nuntuk hasil yang maksimal agar benar-benar terlihat bersih.\n\t \n\tjika sudah merasa bersih selalu ku lakukan memakai toner dari TBS (Tea Tree) \nbiar terdapat nutrisi pada kulit kita, setelah toner lanjut menggunakan serum dari TBS\n(Tea Tree) agar kulit lebih fresh dan kenyal selesai serum ku lanjutkan menggunakan \nPelembab Wajah dari Jeju Aloe Vera Gel yang gunanya untuk melembabkan wajah. \n\t\n\t\tSetelah itu ku tidur dengan nyenyak:)\n\t\n");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout TrutinLayout = new javax.swing.GroupLayout(Trutin);
        Trutin.setLayout(TrutinLayout);
        TrutinLayout.setHorizontalGroup(
            TrutinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrutinLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrutinLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        TrutinLayout.setVerticalGroup(
            TrutinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrutinLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bodybawah.add(Trutin, "card6");

        Tdry.setBackground(new java.awt.Color(22, 160, 133));

        jLabel1.setFont(new java.awt.Font("DilleniaUPC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/icons8-lips-40.png"))); // NOI18N
        jLabel1.setText("HELLO BEUATYFULL\n");
        jLabel1.setIconTextGap(10);

        jScrollPane1.setForeground(new java.awt.Color(204, 153, 255));
        jScrollPane1.setFont(new java.awt.Font("DilleniaUPC", 0, 18)); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(22, 160, 133));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 204));
        jTextArea1.setText("Banyak berbagai produk skincare yang di iklan kan melalui televise maupun media social,\nKadang tanpa pertimbangan banyak yang Cuma asal membeli dan tidak tau cocok dengan \njenis kulit kita atau tidak. Kalo kalian memiliki jenis kulit yang kering, \nsebaiknya kita cari tahu produk skincare apa yang bagus yang sesuai untuk kulit kering.\n");
        jTextArea1.setBorder(null);
        jTextArea1.setSelectionColor(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/soap.png"))); // NOI18N
        jLabel2.setText("Pilihan skin cleanser yang lembut");

        jLabel3.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/fresh.png"))); // NOI18N
        jLabel3.setText("Bawalah skin refresher saat kita beraktivitas");

        jLabel4.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/cream.png"))); // NOI18N
        jLabel4.setText("Gunakan moisturizing cream");

        jLabel5.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/toner.png"))); // NOI18N
        jLabel5.setText("Pake toner untuk menyegarkan kulit");

        jLabel6.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/sunscreen.png"))); // NOI18N
        jLabel6.setText("Gunakan water-based sun screen");

        jLabel7.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/masker.png"))); // NOI18N
        jLabel7.setText("Maskeran dua kali seminggu");

        jLabel8.setFont(new java.awt.Font("DilleniaUPC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasindividu/icons8-foundation-makeup-40.png"))); // NOI18N
        jLabel8.setText("Oleskan water-based liquid faoundation ");

        javax.swing.GroupLayout TdryLayout = new javax.swing.GroupLayout(Tdry);
        Tdry.setLayout(TdryLayout);
        TdryLayout.setHorizontalGroup(
            TdryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TdryLayout.createSequentialGroup()
                .addGroup(TdryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TdryLayout.createSequentialGroup()
                        .addGroup(TdryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TdryLayout.createSequentialGroup()
                                .addContainerGap(101, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TdryLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TdryLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(TdryLayout.createSequentialGroup()
                .addGroup(TdryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TdryLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1))
                    .addGroup(TdryLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TdryLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TdryLayout.setVerticalGroup(
            TdryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TdryLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(TdryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TdryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TdryLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8))
                    .addGroup(TdryLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        bodybawah.add(Tdry, "card2");

        getContentPane().add(bodybawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 780, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BDryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDryActionPerformed
        // TODO add your handling code here:
        
        bodybawah.removeAll();
        bodybawah.repaint();
        bodybawah.revalidate();

        //add panel
        bodybawah.add(Toil);
        bodybawah.repaint();
        bodybawah.revalidate();
        
    }//GEN-LAST:event_BDryActionPerformed

    private void BcombiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcombiActionPerformed
        // TODO add your handling code here:
        bodybawah.removeAll();
        bodybawah.repaint();
        bodybawah.revalidate();

        //add panel
        bodybawah.add(Tkombi);
        bodybawah.repaint();
        bodybawah.revalidate();
    }//GEN-LAST:event_BcombiActionPerformed

    private void BOliyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOliyActionPerformed
        // TODO add your handling code here:
        bodybawah.removeAll();
        bodybawah.repaint();
        bodybawah.revalidate();

        //add panel
        bodybawah.add(Tdry);
        bodybawah.repaint();
        bodybawah.revalidate();
    }//GEN-LAST:event_BOliyActionPerformed

    private void BHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHomeActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_BHomeActionPerformed

    private void rutinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutinActionPerformed
        // TODO add your handling code here:
        bodybawah.removeAll();
        bodybawah.repaint();
        bodybawah.revalidate();

        //add panel
        bodybawah.add(Trutin);
        bodybawah.repaint();
        bodybawah.revalidate();
    }//GEN-LAST:event_rutinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDry;
    private javax.swing.JButton BHome;
    private javax.swing.JButton BOliy;
    private javax.swing.JButton Bcombi;
    private javax.swing.JPanel Tdry;
    private javax.swing.JPanel Tkombi;
    private javax.swing.JPanel Toil;
    private javax.swing.JPanel Trutin;
    private javax.swing.JPanel aboutme;
    private javax.swing.JPanel bodyatas;
    private javax.swing.JPanel bodybawah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JButton rutin;
    // End of variables declaration//GEN-END:variables
}
